variable "domain" {
  type    = "string"
  default = "default"
}

variable "service" {
  type = "string"
}

variable "global_services" {
  type = "map"

  default = {
    "IAM" = true
    "S3"  = true
  }
}

variable "service_names" {
  type = "map"

  default = {
    "IAM"     = "identity_iam"
    "EC2"     = "compute_ec2"
    "S3"      = "storage_s3"
    "RDS"     = "database_rds"
    "VPC"     = "networking_vpc"
    "Route53" = "networking_route53"
  }
}

variable "readonlyaccess_groups" {
  type    = "list"
  default = ["AWSDirectConnectReadOnlyAccess", "AmazonGlacierReadOnlyAccess", "AutoScalingConsoleReadOnlyAccess", "AWSElasticBeanstalkReadOnlyAccess", "AWSCertificateManagerReadOnly", "AutoScalingReadOnlyAccess", "AWSMobileHub_ReadOnly", "AmazonCloudDirectoryReadOnlyAccess", "AmazonRoute53DomainsReadOnlyAccess", "AWSStorageGatewayReadOnlyAccess", "QuickSightAccessForS3StorageManagementAnalyticsReadOnly", "AmazonEC2ContainerRegistryReadOnly", "AmazonRedshiftReadOnlyAccess", "AmazonEC2ReadOnlyAccess", "AWSXrayReadOnlyAccess", "AmazonElasticMapReduceReadOnlyAccess", "AWSDirectoryServiceReadOnlyAccess", "AmazonVPCReadOnlyAccess", "CloudWatchEventsReadOnlyAccess", "AmazonKinesisAnalyticsReadOnly", "AWSCodePipelineReadOnlyAccess", "ReadOnlyAccess", "AmazonRekognitionReadOnlyAccess", "AWSCodeDeployReadOnlyAccess", "AmazonSESReadOnlyAccess", "AWSWAFReadOnlyAccess", "AmazonMechanicalTurkReadOnly", "AmazonKinesisReadOnlyAccess", "AmazonElastiCacheReadOnlyAccess", "AmazonElasticFileSystemReadOnlyAccess", "AmazonZocaloReadOnlyAccess", "AWSCloudHSMReadOnlyAccess", "AmazonRoute53ReadOnlyAccess", "AmazonSQSReadOnlyAccess", "AmazonMachineLearningReadOnlyAccess", "AmazonDynamoDBReadOnlyAccess", "AmazonSNSReadOnlyAccess", "AmazonS3ReadOnlyAccess", "CloudWatchLogsReadOnlyAccess", "AmazonKinesisFirehoseReadOnlyAccess", "AmazonPollyReadOnlyAccess", "ServiceCatalogAdminReadOnlyAccess", "AWSCodeCommitReadOnly", "AmazonCognitoReadOnly", "AWSCloudTrailReadOnlyAccess", "AmazonLexReadOnly", "AmazonElasticTranscoderReadOnlyAccess", "AWSIoTConfigReadOnlyAccess", "AmazonWorkMailReadOnlyAccess", "ResourceGroupsandTagEditorReadOnlyAccess", "AWSCodeBuildReadOnlyAccess", "CloudFrontReadOnlyAccess", "IAMReadOnlyAccess", "AmazonRDSReadOnlyAccess", "AWSLambdaReadOnlyAccess", "CloudWatchReadOnlyAccess", "AWSImportExportReadOnlyAccess", "AmazonSSMReadOnlyAccess", "AWSStepFunctionsReadOnlyAccess", "AmazonESReadOnlyAccess", "CloudSearchReadOnlyAccess", "AWSCloudFormationReadOnlyAccess", "AmazonAppStreamReadOnlyAccess", "AmazonInspectorReadOnlyAccess"]
}

variable "readonlyaccess_groups_policies" {
  type = "map"

  default = {
    "AWSDirectConnectReadOnlyAccess"                          = "arn:aws:iam::aws:policy/AWSDirectConnectReadOnlyAccess"
    "AmazonGlacierReadOnlyAccess"                             = "arn:aws:iam::aws:policy/AmazonGlacierReadOnlyAccess"
    "AutoScalingConsoleReadOnlyAccess"                        = "arn:aws:iam::aws:policy/AutoScalingConsoleReadOnlyAccess"
    "AWSElasticBeanstalkReadOnlyAccess"                       = "arn:aws:iam::aws:policy/AWSElasticBeanstalkReadOnlyAccess"
    "AWSCertificateManagerReadOnly"                           = "arn:aws:iam::aws:policy/AWSCertificateManagerReadOnly"
    "AutoScalingReadOnlyAccess"                               = "arn:aws:iam::aws:policy/AutoScalingReadOnlyAccess"
    "AWSMobileHub_ReadOnly"                                   = "arn:aws:iam::aws:policy/AWSMobileHub_ReadOnly"
    "AmazonCloudDirectoryReadOnlyAccess"                      = "arn:aws:iam::aws:policy/AmazonCloudDirectoryReadOnlyAccess"
    "AmazonRoute53DomainsReadOnlyAccess"                      = "arn:aws:iam::aws:policy/AmazonRoute53DomainsReadOnlyAccess"
    "AWSStorageGatewayReadOnlyAccess"                         = "arn:aws:iam::aws:policy/AWSStorageGatewayReadOnlyAccess"
    "QuickSightAccessForS3StorageManagementAnalyticsReadOnly" = "arn:aws:iam::aws:policy/service-role/QuickSightAccessForS3StorageManagementAnalyticsReadOnly"
    "AmazonEC2ContainerRegistryReadOnly"                      = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    "AmazonRedshiftReadOnlyAccess"                            = "arn:aws:iam::aws:policy/AmazonRedshiftReadOnlyAccess"
    "AmazonEC2ReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
    "AWSXrayReadOnlyAccess"                                   = "arn:aws:iam::aws:policy/AWSXrayReadOnlyAccess"
    "AmazonElasticMapReduceReadOnlyAccess"                    = "arn:aws:iam::aws:policy/AmazonElasticMapReduceReadOnlyAccess"
    "AWSDirectoryServiceReadOnlyAccess"                       = "arn:aws:iam::aws:policy/AWSDirectoryServiceReadOnlyAccess"
    "AmazonVPCReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess"
    "CloudWatchEventsReadOnlyAccess"                          = "arn:aws:iam::aws:policy/CloudWatchEventsReadOnlyAccess"
    "AmazonKinesisAnalyticsReadOnly"                          = "arn:aws:iam::aws:policy/AmazonKinesisAnalyticsReadOnly"
    "AWSCodePipelineReadOnlyAccess"                           = "arn:aws:iam::aws:policy/AWSCodePipelineReadOnlyAccess"
    "ReadOnlyAccess"                                          = "arn:aws:iam::aws:policy/ReadOnlyAccess"
    "AmazonRekognitionReadOnlyAccess"                         = "arn:aws:iam::aws:policy/AmazonRekognitionReadOnlyAccess"
    "AWSCodeDeployReadOnlyAccess"                             = "arn:aws:iam::aws:policy/AWSCodeDeployReadOnlyAccess"
    "AmazonSESReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonSESReadOnlyAccess"
    "AWSWAFReadOnlyAccess"                                    = "arn:aws:iam::aws:policy/AWSWAFReadOnlyAccess"
    "AmazonMechanicalTurkReadOnly"                            = "arn:aws:iam::aws:policy/AmazonMechanicalTurkReadOnly"
    "AmazonKinesisReadOnlyAccess"                             = "arn:aws:iam::aws:policy/AmazonKinesisReadOnlyAccess"
    "AmazonElastiCacheReadOnlyAccess"                         = "arn:aws:iam::aws:policy/AmazonElastiCacheReadOnlyAccess"
    "AmazonElasticFileSystemReadOnlyAccess"                   = "arn:aws:iam::aws:policy/AmazonElasticFileSystemReadOnlyAccess"
    "AmazonZocaloReadOnlyAccess"                              = "arn:aws:iam::aws:policy/AmazonZocaloReadOnlyAccess"
    "AWSCloudHSMReadOnlyAccess"                               = "arn:aws:iam::aws:policy/AWSCloudHSMReadOnlyAccess"
    "AmazonRoute53ReadOnlyAccess"                             = "arn:aws:iam::aws:policy/AmazonRoute53ReadOnlyAccess"
    "AmazonSQSReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonSQSReadOnlyAccess"
    "AmazonMachineLearningReadOnlyAccess"                     = "arn:aws:iam::aws:policy/AmazonMachineLearningReadOnlyAccess"
    "AmazonDynamoDBReadOnlyAccess"                            = "arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess"
    "AmazonSNSReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonSNSReadOnlyAccess"
    "AmazonS3ReadOnlyAccess"                                  = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
    "CloudWatchLogsReadOnlyAccess"                            = "arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess"
    "AmazonKinesisFirehoseReadOnlyAccess"                     = "arn:aws:iam::aws:policy/AmazonKinesisFirehoseReadOnlyAccess"
    "AmazonPollyReadOnlyAccess"                               = "arn:aws:iam::aws:policy/AmazonPollyReadOnlyAccess"
    "ServiceCatalogAdminReadOnlyAccess"                       = "arn:aws:iam::aws:policy/ServiceCatalogAdminReadOnlyAccess"
    "AWSCodeCommitReadOnly"                                   = "arn:aws:iam::aws:policy/AWSCodeCommitReadOnly"
    "AmazonCognitoReadOnly"                                   = "arn:aws:iam::aws:policy/AmazonCognitoReadOnly"
    "AWSCloudTrailReadOnlyAccess"                             = "arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess"
    "AmazonLexReadOnly"                                       = "arn:aws:iam::aws:policy/AmazonLexReadOnly"
    "AmazonElasticTranscoderReadOnlyAccess"                   = "arn:aws:iam::aws:policy/AmazonElasticTranscoderReadOnlyAccess"
    "AWSIoTConfigReadOnlyAccess"                              = "arn:aws:iam::aws:policy/AWSIoTConfigReadOnlyAccess"
    "AmazonWorkMailReadOnlyAccess"                            = "arn:aws:iam::aws:policy/AmazonWorkMailReadOnlyAccess"
    "ResourceGroupsandTagEditorReadOnlyAccess"                = "arn:aws:iam::aws:policy/ResourceGroupsandTagEditorReadOnlyAccess"
    "AWSCodeBuildReadOnlyAccess"                              = "arn:aws:iam::aws:policy/AWSCodeBuildReadOnlyAccess"
    "CloudFrontReadOnlyAccess"                                = "arn:aws:iam::aws:policy/CloudFrontReadOnlyAccess"
    "IAMReadOnlyAccess"                                       = "arn:aws:iam::aws:policy/IAMReadOnlyAccess"
    "AmazonRDSReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess"
    "AWSLambdaReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess"
    "CloudWatchReadOnlyAccess"                                = "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess"
    "AWSImportExportReadOnlyAccess"                           = "arn:aws:iam::aws:policy/AWSImportExportReadOnlyAccess"
    "AmazonSSMReadOnlyAccess"                                 = "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
    "AWSStepFunctionsReadOnlyAccess"                          = "arn:aws:iam::aws:policy/AWSStepFunctionsReadOnlyAccess"
    "AmazonESReadOnlyAccess"                                  = "arn:aws:iam::aws:policy/AmazonESReadOnlyAccess"
    "CloudSearchReadOnlyAccess"                               = "arn:aws:iam::aws:policy/CloudSearchReadOnlyAccess"
    "AWSCloudFormationReadOnlyAccess"                         = "arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess"
    "AmazonAppStreamReadOnlyAccess"                           = "arn:aws:iam::aws:policy/AmazonAppStreamReadOnlyAccess"
    "AmazonInspectorReadOnlyAccess"                           = "arn:aws:iam::aws:policy/AmazonInspectorReadOnlyAccess"
  }
}

variable "readonlyaccess_groups_policies_description" {
  type = "map"

  default = {
    "AWSDirectConnectReadOnlyAccess"                          = "Provides read only access to AWS Direct Connect via the AWS Management Console."
    "AmazonGlacierReadOnlyAccess"                             = "Provides read only access to Amazon Glacier via the AWS Management Console."
    "AutoScalingConsoleReadOnlyAccess"                        = "Provides read-only access to Auto Scaling via the AWS Management Console."
    "AWSElasticBeanstalkReadOnlyAccess"                       = "Provides read only access to AWS Elastic Beanstalk via the AWS Management Console."
    "AWSCertificateManagerReadOnly"                           = "Provides read only access to AWS Certificate Manager (ACM)."
    "AutoScalingReadOnlyAccess"                               = "Provides read-only access to Auto Scaling. "
    "AWSMobileHub_ReadOnly"                                   = "This policy may be attached to any User, Role, or Group, in order to grant users permission to list and view projects in AWS Mobile Hub. This also includes permissions to generate and download sample mobile app source code for each Mobile Hub project. It does not allow the user to modify any configuration for any Mobile Hub project."
    "AmazonCloudDirectoryReadOnlyAccess"                      = "Provides read only access to Amazon Cloud Directory Service. "
    "AmazonRoute53DomainsReadOnlyAccess"                      = "Provides access to Route53 Domains list and actions."
    "AWSStorageGatewayReadOnlyAccess"                         = "Provides access to AWS Storage Gateway via the AWS Management Console."
    "QuickSightAccessForS3StorageManagementAnalyticsReadOnly" = "Policy used by QuickSight team to access customer data produced by S3 Storage Management Analytics."
    "AmazonEC2ContainerRegistryReadOnly"                      = "Provides read-only access to Amazon EC2 Container Registry repositories."
    "AmazonRedshiftReadOnlyAccess"                            = "Provides read only access to Amazon Redshift via the AWS Management Console."
    "AmazonEC2ReadOnlyAccess"                                 = "Provides read only access to Amazon EC2 via the AWS Management Console."
    "AWSXrayReadOnlyAccess"                                   = "AWS X-Ray read only managed policy"
    "AmazonElasticMapReduceReadOnlyAccess"                    = "Provides read only access to Amazon Elastic MapReduce via the AWS Management Console."
    "AWSDirectoryServiceReadOnlyAccess"                       = "Provides read only access to AWS Directory Service."
    "AmazonVPCReadOnlyAccess"                                 = "Provides read only access to Amazon VPC via the AWS Management Console."
    "CloudWatchEventsReadOnlyAccess"                          = "Provides read only access to Amazon CloudWatch Events."
    "AmazonKinesisAnalyticsReadOnly"                          = "Provides read-only access to Amazon Kinesis Analytics via the AWS Management Console."
    "AWSCodePipelineReadOnlyAccess"                           = "Provides read only access to AWS CodePipeline via the AWS Management Console."
    "ReadOnlyAccess"                                          = "Provides read-only access to AWS services and resources."
    "AmazonRekognitionReadOnlyAccess"                         = "Access to all Read rekognition APIs"
    "AWSCodeDeployReadOnlyAccess"                             = "Provides read only access to CodeDeploy resources."
    "AmazonSESReadOnlyAccess"                                 = "Provides read only access to Amazon SES via the AWS Management Console."
    "AWSWAFReadOnlyAccess"                                    = "Provides read only access to AWS WAF actions."
    "AmazonMechanicalTurkReadOnly"                            = "Provides access to read only APIs in Amazon Mechanical Turk."
    "AmazonKinesisReadOnlyAccess"                             = "Provides read only access to all streams via the AWS Management Console."
    "AmazonElastiCacheReadOnlyAccess"                         = "Provides read only access to Amazon ElastiCache via the AWS Management Console."
    "AmazonElasticFileSystemReadOnlyAccess"                   = "Provides read only access to Amazon EFS via the AWS Management Console."
    "AmazonZocaloReadOnlyAccess"                              = "Provides read only access to Amazon Zocalo"
    "AWSCloudHSMReadOnlyAccess"                               = "Provides read only access to all CloudHSM resources."
    "AmazonRoute53ReadOnlyAccess"                             = "Provides read only access to all Amazon Route 53 via the AWS Management Console."
    "AmazonSQSReadOnlyAccess"                                 = "Provides read only access to Amazon SQS via the AWS Management Console."
    "AmazonMachineLearningReadOnlyAccess"                     = "Provides read only access to Amazon Machine Learning resources."
    "AmazonDynamoDBReadOnlyAccess"                            = "Provides read only access to Amazon DynamoDB via the AWS Management Console."
    "AmazonSNSReadOnlyAccess"                                 = "Provides read only access to Amazon SNS via the AWS Management Console."
    "AmazonS3ReadOnlyAccess"                                  = "Provides read only access to all buckets via the AWS Management Console."
    "CloudWatchLogsReadOnlyAccess"                            = "Provides read only access to CloudWatch Logs"
    "AmazonKinesisFirehoseReadOnlyAccess"                     = "Provides read only access to all Amazon Kinesis Firehose Delivery Streams."
    "AmazonPollyReadOnlyAccess"                               = "Grants read-only access to Amazon Polly resources."
    "ServiceCatalogAdminReadOnlyAccess"                       = "Provides read only access to the service catalog admin console."
    "AWSCodeCommitReadOnly"                                   = "Provides read only access to AWS CodeCommit via the AWS Management Console."
    "AmazonCognitoReadOnly"                                   = "Provides read only access to Amazon Cognito resources."
    "AWSCloudTrailReadOnlyAccess"                             = "Provides read only access to AWS CloudTrail."
    "AmazonLexReadOnly"                                       = "Provides read-only access to Amazon Lex."
    "AmazonElasticTranscoderReadOnlyAccess"                   = "Grants users read-only access to Elastic Transcoder and list access to related services."
    "AWSIoTConfigReadOnlyAccess"                              = "This policy gives read only access to the AWS IoT configuration actions"
    "AmazonWorkMailReadOnlyAccess"                            = "Provides read only access to WorkMail and SES."
    "ResourceGroupsandTagEditorReadOnlyAccess"                = "Provides access to use Resource Groups and Tag Editor, but does not allow editing of tags via the Tag Editor."
    "AWSCodeBuildReadOnlyAccess"                              = "Provides read only access to AWS CodeBuild via the AWS Management Console. Also attach AmazonS3ReadOnlyAccess to provide access to download build artifacts."
    "CloudFrontReadOnlyAccess"                                = "Provides access to CloudFront distribution configuration information and list distributions via the AWS Management Console."
    "IAMReadOnlyAccess"                                       = "Provides read only access to IAM via the AWS Management Console."
    "AmazonRDSReadOnlyAccess"                                 = "Provides read only access to Amazon RDS via the AWS Management Console."
    "AWSLambdaReadOnlyAccess"                                 = "Provides read only access to Lambda, S3, DynamoDB, CloudWatch Metrics and Logs."
    "CloudWatchReadOnlyAccess"                                = "Provides read only access to CloudWatch."
    "AWSImportExportReadOnlyAccess"                           = "Provides read only access to the jobs created under the AWS account."
    "AmazonSSMReadOnlyAccess"                                 = "Provides read only access to Amazon SSM."
    "AWSStepFunctionsReadOnlyAccess"                          = "An access policy for providing a user/role/etc read only access to the AWS StepFunctions service."
    "AmazonESReadOnlyAccess"                                  = "Provides read-only access to the Amazon ES configuration service."
    "CloudSearchReadOnlyAccess"                               = "Provides read only access to the Amazon CloudSearch configuration service."
    "AWSCloudFormationReadOnlyAccess"                         = "Provides access to AWS CloudFormation via the AWS Management Console."
    "AmazonAppStreamReadOnlyAccess"                           = "Provides read only access to Amazon AppStream via the AWS Management Console."
    "AmazonInspectorReadOnlyAccess"                           = "Provides read only access to Amazon Inspector."
  }
}

variable "fullaccess_groups" {
  type    = "list"
  default = ["AWSMarketplaceFullAccess", "AWSHealthFullAccess", "AmazonRDSFullAccess", "AmazonEC2FullAccess", "AWSCodeCommitFullAccess", "AmazonSQSFullAccess", "AWSLambdaFullAccess", "IAMFullAccess", "AmazonInspectorFullAccess", "AmazonElastiCacheFullAccess", "AutoScalingFullAccess", "AWSOpsWorksFullAccess", "AmazonEC2ContainerRegistryFullAccess", "SimpleWorkflowFullAccess", "AmazonS3FullAccess", "AmazonAPIGatewayInvokeFullAccess", "AmazonMobileAnalyticsFullAccess", "AWSMobileHub_FullAccess", "CloudWatchFullAccess", "ServiceCatalogAdminFullAccess", "CloudSearchFullAccess", "AWSCloudHSMFullAccess", "AWSDirectoryServiceFullAccess", "AmazonDynamoDBFullAccess", "AWSCodeDeployFullAccess", "AmazonRoute53DomainsFullAccess", "AmazonAthenaFullAccess", "CloudFrontFullAccess", "AWSCloudTrailFullAccess", "AmazonRedshiftFullAccess", "AmazonKinesisFullAccess", "AmazonRekognitionFullAccess", "AmazonMachineLearningFullAccess", "AWSCodeStarFullAccess", "AWSDataPipeline_FullAccess", "AutoScalingConsoleFullAccess", "AmazonElasticMapReduceFullAccess", "AWSElasticBeanstalkFullAccess", "AmazonSESFullAccess", "AmazonDynamoDBFullAccesswithDataPipeline", "CloudWatchLogsFullAccess", "AmazonElasticTranscoderFullAccess", "AWSMarketplaceMeteringFullAccess", "AWSBatchFullAccess", "AmazonSSMFullAccess", "AmazonEC2ContainerServiceFullAccess", "AWSApplicationDiscoveryServiceFullAccess", "AmazonVPCFullAccess", "AWSImportExportFullAccess", "AmazonMechanicalTurkFullAccess", "AmazonCloudDirectoryFullAccess", "AWSStorageGatewayFullAccess", "ServiceCatalogEndUserFullAccess", "AWSStepFunctionsConsoleFullAccess", "AmazonElasticFileSystemFullAccess", "AmazonZocaloFullAccess", "AmazonAppStreamFullAccess", "AmazonESFullAccess", "AWSWAFFullAccess", "AmazonKinesisFirehoseFullAccess", "ResourceGroupsandTagEditorFullAccess", "AWSDeviceFarmFullAccess", "AWSCodePipelineFullAccess", "AWSXrayFullAccess", "AWSDirectConnectFullAccess", "AmazonKinesisAnalyticsFullAccess", "AmazonGlacierFullAccess", "AmazonWorkMailFullAccess", "AWSIoTFullAccess", "AmazonPollyFullAccess", "AmazonLexFullAccess", "AmazonSNSFullAccess", "AWSGreengrassFullAccess", "AmazonRoute53FullAccess", "AWSStepFunctionsFullAccess", "AWSCertificateManagerFullAccess", "CloudWatchEventsFullAccess"]
}

variable "fullaccess_groups_policies" {
  type = "map"

  default = {
    "AWSMarketplaceFullAccess"                 = "arn:aws:iam::aws:policy/AWSMarketplaceFullAccess"
    "AWSHealthFullAccess"                      = "arn:aws:iam::aws:policy/AWSHealthFullAccess"
    "AmazonRDSFullAccess"                      = "arn:aws:iam::aws:policy/AmazonRDSFullAccess"
    "AmazonEC2FullAccess"                      = "arn:aws:iam::aws:policy/AmazonEC2FullAccess"
    "AWSCodeCommitFullAccess"                  = "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess"
    "AmazonSQSFullAccess"                      = "arn:aws:iam::aws:policy/AmazonSQSFullAccess"
    "AWSLambdaFullAccess"                      = "arn:aws:iam::aws:policy/AWSLambdaFullAccess"
    "IAMFullAccess"                            = "arn:aws:iam::aws:policy/IAMFullAccess"
    "AmazonInspectorFullAccess"                = "arn:aws:iam::aws:policy/AmazonInspectorFullAccess"
    "AmazonElastiCacheFullAccess"              = "arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess"
    "AutoScalingFullAccess"                    = "arn:aws:iam::aws:policy/AutoScalingFullAccess"
    "AWSOpsWorksFullAccess"                    = "arn:aws:iam::aws:policy/AWSOpsWorksFullAccess"
    "AmazonEC2ContainerRegistryFullAccess"     = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
    "SimpleWorkflowFullAccess"                 = "arn:aws:iam::aws:policy/SimpleWorkflowFullAccess"
    "AmazonS3FullAccess"                       = "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    "AmazonAPIGatewayInvokeFullAccess"         = "arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess"
    "AmazonMobileAnalyticsFullAccess"          = "arn:aws:iam::aws:policy/AmazonMobileAnalyticsFullAccess"
    "AWSMobileHub_FullAccess"                  = "arn:aws:iam::aws:policy/AWSMobileHub_FullAccess"
    "CloudWatchFullAccess"                     = "arn:aws:iam::aws:policy/CloudWatchFullAccess"
    "ServiceCatalogAdminFullAccess"            = "arn:aws:iam::aws:policy/ServiceCatalogAdminFullAccess"
    "CloudSearchFullAccess"                    = "arn:aws:iam::aws:policy/CloudSearchFullAccess"
    "AWSCloudHSMFullAccess"                    = "arn:aws:iam::aws:policy/AWSCloudHSMFullAccess"
    "AWSDirectoryServiceFullAccess"            = "arn:aws:iam::aws:policy/AWSDirectoryServiceFullAccess"
    "AmazonDynamoDBFullAccess"                 = "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
    "AWSCodeDeployFullAccess"                  = "arn:aws:iam::aws:policy/AWSCodeDeployFullAccess"
    "AmazonRoute53DomainsFullAccess"           = "arn:aws:iam::aws:policy/AmazonRoute53DomainsFullAccess"
    "AmazonAthenaFullAccess"                   = "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
    "CloudFrontFullAccess"                     = "arn:aws:iam::aws:policy/CloudFrontFullAccess"
    "AWSCloudTrailFullAccess"                  = "arn:aws:iam::aws:policy/AWSCloudTrailFullAccess"
    "AmazonRedshiftFullAccess"                 = "arn:aws:iam::aws:policy/AmazonRedshiftFullAccess"
    "AmazonKinesisFullAccess"                  = "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
    "AmazonRekognitionFullAccess"              = "arn:aws:iam::aws:policy/AmazonRekognitionFullAccess"
    "AmazonMachineLearningFullAccess"          = "arn:aws:iam::aws:policy/AmazonMachineLearningFullAccess"
    "AWSCodeStarFullAccess"                    = "arn:aws:iam::aws:policy/AWSCodeStarFullAccess"
    "AWSDataPipeline_FullAccess"               = "arn:aws:iam::aws:policy/AWSDataPipeline_FullAccess"
    "AutoScalingConsoleFullAccess"             = "arn:aws:iam::aws:policy/AutoScalingConsoleFullAccess"
    "AmazonElasticMapReduceFullAccess"         = "arn:aws:iam::aws:policy/AmazonElasticMapReduceFullAccess"
    "AWSElasticBeanstalkFullAccess"            = "arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess"
    "AmazonSESFullAccess"                      = "arn:aws:iam::aws:policy/AmazonSESFullAccess"
    "AmazonDynamoDBFullAccesswithDataPipeline" = "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccesswithDataPipeline"
    "CloudWatchLogsFullAccess"                 = "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
    "AmazonElasticTranscoderFullAccess"        = "arn:aws:iam::aws:policy/AmazonElasticTranscoderFullAccess"
    "AWSMarketplaceMeteringFullAccess"         = "arn:aws:iam::aws:policy/AWSMarketplaceMeteringFullAccess"
    "AWSBatchFullAccess"                       = "arn:aws:iam::aws:policy/AWSBatchFullAccess"
    "AmazonSSMFullAccess"                      = "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
    "AmazonEC2ContainerServiceFullAccess"      = "arn:aws:iam::aws:policy/AmazonEC2ContainerServiceFullAccess"
    "AWSApplicationDiscoveryServiceFullAccess" = "arn:aws:iam::aws:policy/AWSApplicationDiscoveryServiceFullAccess"
    "AmazonVPCFullAccess"                      = "arn:aws:iam::aws:policy/AmazonVPCFullAccess"
    "AWSImportExportFullAccess"                = "arn:aws:iam::aws:policy/AWSImportExportFullAccess"
    "AmazonMechanicalTurkFullAccess"           = "arn:aws:iam::aws:policy/AmazonMechanicalTurkFullAccess"
    "AmazonCloudDirectoryFullAccess"           = "arn:aws:iam::aws:policy/AmazonCloudDirectoryFullAccess"
    "AWSStorageGatewayFullAccess"              = "arn:aws:iam::aws:policy/AWSStorageGatewayFullAccess"
    "ServiceCatalogEndUserFullAccess"          = "arn:aws:iam::aws:policy/ServiceCatalogEndUserFullAccess"
    "AWSStepFunctionsConsoleFullAccess"        = "arn:aws:iam::aws:policy/AWSStepFunctionsConsoleFullAccess"
    "AmazonElasticFileSystemFullAccess"        = "arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess"
    "AmazonZocaloFullAccess"                   = "arn:aws:iam::aws:policy/AmazonZocaloFullAccess"
    "AmazonAppStreamFullAccess"                = "arn:aws:iam::aws:policy/AmazonAppStreamFullAccess"
    "AmazonESFullAccess"                       = "arn:aws:iam::aws:policy/AmazonESFullAccess"
    "AWSWAFFullAccess"                         = "arn:aws:iam::aws:policy/AWSWAFFullAccess"
    "AmazonKinesisFirehoseFullAccess"          = "arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess"
    "ResourceGroupsandTagEditorFullAccess"     = "arn:aws:iam::aws:policy/ResourceGroupsandTagEditorFullAccess"
    "AWSDeviceFarmFullAccess"                  = "arn:aws:iam::aws:policy/AWSDeviceFarmFullAccess"
    "AWSCodePipelineFullAccess"                = "arn:aws:iam::aws:policy/AWSCodePipelineFullAccess"
    "AWSXrayFullAccess"                        = "arn:aws:iam::aws:policy/AWSXrayFullAccess"
    "AWSDirectConnectFullAccess"               = "arn:aws:iam::aws:policy/AWSDirectConnectFullAccess"
    "AmazonKinesisAnalyticsFullAccess"         = "arn:aws:iam::aws:policy/AmazonKinesisAnalyticsFullAccess"
    "AmazonGlacierFullAccess"                  = "arn:aws:iam::aws:policy/AmazonGlacierFullAccess"
    "AmazonWorkMailFullAccess"                 = "arn:aws:iam::aws:policy/AmazonWorkMailFullAccess"
    "AWSIoTFullAccess"                         = "arn:aws:iam::aws:policy/AWSIoTFullAccess"
    "AmazonPollyFullAccess"                    = "arn:aws:iam::aws:policy/AmazonPollyFullAccess"
    "AmazonLexFullAccess"                      = "arn:aws:iam::aws:policy/AmazonLexFullAccess"
    "AmazonSNSFullAccess"                      = "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
    "AWSGreengrassFullAccess"                  = "arn:aws:iam::aws:policy/AWSGreengrassFullAccess"
    "AmazonRoute53FullAccess"                  = "arn:aws:iam::aws:policy/AmazonRoute53FullAccess"
    "AWSStepFunctionsFullAccess"               = "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
    "AWSCertificateManagerFullAccess"          = "arn:aws:iam::aws:policy/AWSCertificateManagerFullAccess"
    "CloudWatchEventsFullAccess"               = "arn:aws:iam::aws:policy/CloudWatchEventsFullAccess"
  }
}

variable "fullaccess_groups_policies_description" {
  type = "map"

  default = {
    "AWSMarketplaceFullAccess"                 = "Provides the ability to subscribe and unsubscribe to AWS Marketplace software, allows users to manage Marketplace software instances from the Marketplace 'Your Software' page, and provides administrative access to EC2."
    "AWSHealthFullAccess"                      = "Allows full access to the AWS Health Apis and Notifications and the Personal Health Dashboard"
    "AmazonRDSFullAccess"                      = "Provides full access to Amazon RDS via the AWS Management Console."
    "AmazonEC2FullAccess"                      = "Provides full access to Amazon EC2 via the AWS Management Console."
    "AWSCodeCommitFullAccess"                  = "Provides full access to AWS CodeCommit via the AWS Management Console."
    "AmazonSQSFullAccess"                      = "Provides full access to Amazon SQS via the AWS Management Console."
    "AWSLambdaFullAccess"                      = "Provides full access to Lambda, S3, DynamoDB, CloudWatch Metrics and Logs."
    "IAMFullAccess"                            = "Provides full access to IAM via the AWS Management Console."
    "AmazonInspectorFullAccess"                = "Provides full access to Amazon Inspector."
    "AmazonElastiCacheFullAccess"              = "Provides full access to Amazon ElastiCache via the AWS Management Console."
    "AutoScalingFullAccess"                    = "Provides full access to Auto Scaling."
    "AWSOpsWorksFullAccess"                    = "Provides full access to AWS OpsWorks."
    "AmazonEC2ContainerRegistryFullAccess"     = "Provides administrative access to Amazon ECR resources"
    "SimpleWorkflowFullAccess"                 = "Provides full access to the Simple Workflow configuration service."
    "AmazonS3FullAccess"                       = "Provides full access to all buckets via the AWS Management Console."
    "AmazonAPIGatewayInvokeFullAccess"         = "Provides full access to invoke APIs in Amazon API Gateway."
    "AmazonMobileAnalyticsFullAccess"          = "Provides full access to all application resources."
    "AWSMobileHub_FullAccess"                  = "This policy may be attached to any User, Role, or Group, in order to grant users permission to create, delete, and modify projects (and their associated AWS resources) in AWS Mobile Hub. This also includes permissions to generate and download sample mobile app source code for each Mobile Hub project."
    "CloudWatchFullAccess"                     = "Provides full access to CloudWatch."
    "ServiceCatalogAdminFullAccess"            = "Provides full access to the service catalog admin console."
    "CloudSearchFullAccess"                    = "Provides full access to the Amazon CloudSearch configuration service."
    "AWSCloudHSMFullAccess"                    = "Provides full access to all CloudHSM resources."
    "AWSDirectoryServiceFullAccess"            = "Provides full access to AWS Directory Service."
    "AmazonDynamoDBFullAccess"                 = "Provides full access to Amazon DynamoDB via the AWS Management Console."
    "AWSCodeDeployFullAccess"                  = "Provides full access to CodeDeploy resources."
    "AmazonRoute53DomainsFullAccess"           = "Provides full access to all Route53 Domains actions and Create Hosted Zone to allow Hosted Zone creation as part of domain registrations."
    "AmazonAthenaFullAccess"                   = "Provide full access to Amazon Athena and scoped access to the dependencies needed to enable querying, writing results, and data management."
    "CloudFrontFullAccess"                     = "Provides full access to the CloudFront console plus the ability to list Amazon S3 buckets via the AWS Management Console."
    "AWSCloudTrailFullAccess"                  = "Provides full access to AWS CloudTrail."
    "AmazonRedshiftFullAccess"                 = "Provides full access to Amazon Redshift via the AWS Management Console."
    "AmazonKinesisFullAccess"                  = "Provides full access to all streams via the AWS Management Console."
    "AmazonRekognitionFullAccess"              = "Access to all Amazon Rekognition APIs"
    "AmazonMachineLearningFullAccess"          = "Provides full access to Amazon Machine Learning resources."
    "AWSCodeStarFullAccess"                    = "Provides full access to AWS CodeStar via the AWS Management Console."
    "AWSDataPipeline_FullAccess"               = "Provides full access to Data Pipeline, list access for S3, DynamoDB, Redshift, RDS, SNS, and IAM roles, and passRole access for default Roles."
    "AutoScalingConsoleFullAccess"             = "Provides full access to Auto Scaling via the AWS Management Console."
    "AmazonElasticMapReduceFullAccess"         = "Provides full access to Amazon Elastic MapReduce and underlying services that it requires such as EC2 and S3"
    "AWSElasticBeanstalkFullAccess"            = "Provides full access to AWS Elastic Beanstalk and underlying services that it requires such as S3 and EC2."
    "AmazonSESFullAccess"                      = "Profiles full access to Amazon SES via the AWS Management Console."
    "AmazonDynamoDBFullAccesswithDataPipeline" = "Provides full access to Amazon DynamoDB including Export/Import using AWS Data Pipeline via the AWS Management Console."
    "CloudWatchLogsFullAccess"                 = "Provides full access to CloudWatch Logs"
    "AmazonElasticTranscoderFullAccess"        = "Grants users full access to Elastic Transcoder and the access to associated services that is required for full Elastic Transcoder functionality."
    "AWSMarketplaceMeteringFullAccess"         = "Provides full access to AWS Marketplace Metering."
    "AWSBatchFullAccess"                       = "Provides full access for AWS Batch resources."
    "AmazonSSMFullAccess"                      = "Provides full access to Amazon SSM."
    "AmazonEC2ContainerServiceFullAccess"      = "Provides administrative access to Amazon ECS resources."
    "AWSApplicationDiscoveryServiceFullAccess" = "Provides full access to view and tag Configuration Items maintained by the AWS Application Discovery Service "
    "AmazonVPCFullAccess"                      = "Provides full access to Amazon VPC via the AWS Management Console."
    "AWSImportExportFullAccess"                = "Provides read and write access to the jobs created under the AWS account."
    "AmazonMechanicalTurkFullAccess"           = "Provides full access to all APIs in Amazon Mechanical Turk."
    "AmazonCloudDirectoryFullAccess"           = "Provides full access to Amazon Cloud Directory Service. "
    "AWSStorageGatewayFullAccess"              = "Provides full access to AWS Storate Gateway via the AWS Management Console."
    "ServiceCatalogEndUserFullAccess"          = "Provides full access to the service catalog end user console."
    "AWSStepFunctionsConsoleFullAccess"        = "An access policy for providing a user/role/etc access to the AWS StepFunctions console. For a full console experience, in addition to this policy, a user may need iam:PassRole permission on other IAM roles that can be assumed by the service."
    "AmazonElasticFileSystemFullAccess"        = "Provides full access to Amazon EFS via the AWS Management Console."
    "AmazonZocaloFullAccess"                   = "Provides full access to Amazon Zocalo."
    "AmazonAppStreamFullAccess"                = "Provides full access to Amazon AppStream via the AWS Management Console."
    "AmazonESFullAccess"                       = "Provides full access to the Amazon ES configuration service."
    "AWSWAFFullAccess"                         = "Provides full access to AWS WAF actions."
    "AmazonKinesisFirehoseFullAccess"          = "Provides full access to all Amazon Kinesis Firehose Delivery Streams."
    "ResourceGroupsandTagEditorFullAccess"     = "Provides full access to Resource Groups and Tag Editor."
    "AWSDeviceFarmFullAccess"                  = "Provides full access to all AWS Device Farm operations."
    "AWSCodePipelineFullAccess"                = "Provides full access to AWS CodePipeline via the AWS Management Console."
    "AWSXrayFullAccess"                        = "AWS X-Ray full access managed policy"
    "AWSDirectConnectFullAccess"               = "Provides full access to AWS Direct Connect via the AWS Management Console."
    "AmazonKinesisAnalyticsFullAccess"         = "Provides full access to Amazon Kinesis Analytics via the AWS Management Console."
    "AmazonGlacierFullAccess"                  = "Provides full access to Amazon Glacier via the AWS Management Console."
    "AmazonWorkMailFullAccess"                 = "Provides full access to WorkMail, Directory Service, SES, EC2 and read access to KMS metadata."
    "AWSIoTFullAccess"                         = "This policy gives full access to the AWS IoT configuration and messaging actions"
    "AmazonPollyFullAccess"                    = "Grants full access to Amazon Polly service and resources."
    "AmazonLexFullAccess"                      = "Provides full access to Amazon Lex via the AWS Management Console.  Also provides access to create Lex Service Linked Roles and grant Lex permissions to invoke a limited set of Lambda functions."
    "AmazonSNSFullAccess"                      = "Provides full access to Amazon SNS via the AWS Management Console."
    "AWSGreengrassFullAccess"                  = "This policy gives full access to the AWS Greengrass configuration, management and deployment actions"
    "AmazonRoute53FullAccess"                  = "Provides full access to all Amazon Route 53 via the AWS Management Console."
    "AWSStepFunctionsFullAccess"               = "An access policy for providing a user/role/etc access to the AWS StepFunctions API. For full access, in addition to this policy, a user MUST have iam:PassRole permission on at least one IAM role that can be assumed by the service."
    "AWSCertificateManagerFullAccess"          = "Provides full access to AWS Certificate Manager (ACM)"
    "CloudWatchEventsFullAccess"               = "Provides full access to Amazon CloudWatch Events."
  }
}

variable "default_groups" {
  type    = "list"
  default = ["AdministratorAccess", "DatabaseAdministrator", "SystemAdministrator", "NetworkAdministrator", "ServiceCatalogAdminFullAccess", "ServiceCatalogAdminReadOnlyAccess", "AWSCodeBuildAdminAccess", "AmazonAPIGatewayAdministrator", "AmazonWorkSpacesAdmin", "AmazonWorkSpacesApplicationManagerAdminAccess"]
}

variable "default_groups_policies" {
  type = "map"

  default = {
    "AdministratorAccess"                           = "arn:aws:iam::aws:policy/AdministratorAccess"
    "AWSCodeBuildAdminAccess"                       = "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
    "AmazonAPIGatewayAdministrator"                 = "arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator"
    "AmazonWorkSpacesAdmin"                         = "arn:aws:iam::aws:policy/AmazonWorkSpacesAdmin"
    "AmazonWorkSpacesApplicationManagerAdminAccess" = "arn:aws:iam::aws:policy/AmazonWorkSpacesApplicationManagerAdminAccess"
    "ServiceCatalogAdminFullAccess"                 = "arn:aws:iam::aws:policy/ServiceCatalogAdminFullAccess"
    "ServiceCatalogAdminReadOnlyAccess"             = "arn:aws:iam::aws:policy/ServiceCatalogAdminReadOnlyAccess"
    "DatabaseAdministrator"                         = "arn:aws:iam::aws:policy/job-function/DatabaseAdministrator"
    "SystemAdministrator"                           = "arn:aws:iam::aws:policy/job-function/SystemAdministrator"
    "NetworkAdministrator"                          = "arn:aws:iam::aws:policy/job-function/NetworkAdministrator"
    "Billing"                                       = "arn:aws:iam::aws:policy/job-function/Billing"
    "DataScientist"                                 = "arn:aws:iam::aws:policy/job-function/DataScientist"
    "SupportUser"                                   = "arn:aws:iam::aws:policy/job-function/SupportUser"
    "SystemAdministrator"                           = "arn:aws:iam::aws:policy/job-function/SystemAdministrator"
    "ViewOnlyAccess"                                = "arn:aws:iam::aws:policy/job-function/ViewOnlyAccess"
  }
}

variable "default_groups_policies_description" {
  type = "map"

  default = {
    "AdministratorAccess"                           = "Provides full access to AWS services and resources."
    "AWSCodeBuildAdminAccess"                       = "Provides full access to AWS CodeBuild via the AWS Management Console. Also attach AmazonS3ReadOnlyAccess to provide access to download build artifacts, and attach IAMFullAccess to create and manage the service role for CodeBuild."
    "AmazonAPIGatewayAdministrator"                 = "Provides full access to create/edit/delete APIs in Amazon API Gateway via the AWS Management Console."
    "AmazonWorkSpacesAdmin"                         = "Provides access to Amazon WorkSpaces administrative actions via AWS SDK and CLI."
    "AmazonWorkSpacesApplicationManagerAdminAccess" = "Provides administrator access for packaging an application in Amazon WorkSpaces Application Manager."
    "ServiceCatalogAdminFullAccess"                 = "Provides full access to the service catalog admin console."
    "ServiceCatalogAdminReadOnlyAccess"             = "Provides read only access to the service catalog admin console."
    "DatabaseAdministrator"                         = "Grants full access permissions to AWS services and actions required to set up and configure AWS database services."
    "SystemAdministrator"                           = "Grants full access permissions necessary for resources required for application and development operations."
    "NetworkAdministrator"                          = "Grants full access permissions to AWS services and actions required to set up and configure AWS network resources."
    "Billing"                                       = "Grants permissions for billing and cost management. This includes viewing account ussage and viewing and modifying budgets and payment methods."
    "DataScientist"                                 = "Grants permissions to AWS data analytics services."
    "SupportUser"                                   = "This policy grants permissions to troubleshoot and resolve issues in an AWS account. This policy also enables the user to contact AWS support to create and manage cases."
    "SystemAdministrator"                           = "Grants full access permissions necessary for resources required for application and development operations."
    "ViewOnlyAccess"                                = "This policy grants permissions to view resources and basic metadata across all AWS services."
  }
}
